version: '3.9'
services:
  sem_seg_example:
    image: sota_semseg
    container_name: sem_seg_example
    runtime: nvidia
    tty: true
    stdin_open: true
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
