version: '3.9'
services:
  hugface:
    build:
      context: .
    container_name: hugface_example
    runtime: nvidia
    tty: true
    stdin_open: true
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
