FROM pytorch/pytorch:1.13.0-cuda11.6-cudnn8-devel

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y --no-install-recommends \
    wget \
    curl \
    build-essential \
    ninja-build \
    git \
    gcc-8 \
    g++-8 \
    libgl1-mesa-glx \
    libglib2.0-0 \
    libglib2.0-dev \
    vim && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

ENV CC=gcc-8
ENV CXX=g++-8

WORKDIR /workspace
COPY build_msda.sh /workspace/
RUN chmod +x build_msda.sh

RUN git clone https://github.com/fundamentalvision/Deformable-DETR.git /workspace/Deformable-DETR

RUN pip3 install 'git+https://github.com/cocodataset/cocoapi.git#subdirectory=PythonAPI'

RUN git clone https://github.com/MaureenZOU/detectron2-xyz.git /workspace/detectron2-xyz
WORKDIR /workspace/detectron2-xyz
RUN python3 -m pip install .

RUN git clone https://github.com/cocodataset/panopticapi.git /workspace/panopticapi
WORKDIR /workspace/panopticapi
RUN pip3 install .

RUN git clone https://github.com/UX-Decoder/DINOv /workspace/DINOv
WORKDIR /workspace/DINOv

COPY my_demo.py /workspace/DINOv/

# モデルチェックポイント（model_swinT.pth）をダウンロード
RUN wget https://github.com/UX-Decoder/DINOv/releases/download/checkpoint/model_swinT.pth -P /workspace/DINOv
RUN wget https://github.com/UX-Decoder/DINOv/releases/download/checkpoint/model_swinL.pth -P /workspace/DINOv

RUN sed -i '/pycocotools/d' requirements.txt
RUN sed -i '/torch/d' requirements.txt
RUN sed -i '/torchvision/d' requirements.txt
RUN pip install --upgrade pip
RUN python -m pip install -r requirements.txt
RUN python -m pip install markupsafe==2.0.1

